# Generated by Django 5.1.2 on 2024-10-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="cantidad",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
