# Generated by Django 5.1.2 on 2024-10-11 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0002_curso_cantidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="cantidad",
        ),
    ]
