# Generated by Django 5.1.2 on 2024-10-16 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0003_remove_curso_cantidad"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Curso",
            new_name="Cursos",
        ),
    ]
