# Generated by Django 5.1.2 on 2024-10-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0005_estudiantes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiantes",
            name="dni",
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
