# Generated by Django 5.1.2 on 2024-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0006_alter_estudiantes_dni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("legajo", models.IntegerField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
