# Generated by Django 5.1.2 on 2024-10-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iades", "0008_rename_cursos_curso_rename_estudiantes_estudiante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oyente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("curso", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name_plural": "Profesores"},
        ),
    ]
